repository: eliabesilvala/blog
locale: "pt-BR"
logo: "/assets/images/88x88.png"
title: Eliabe Silva
email: eliabe.silva.la@gmail.com
description: Notícias, meliponicultura, tecnologia, tutoriais e muito mais!
twitter_username: eliabesilvala
github_username: eliabesilvala
minimal_mistakes_skin: dark
search: true
title_separator: "|"
google_analytics: G-H6YBMH7RT3

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
url: https://eliabesilva.com.br
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:title/
timezone: America/Recife # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _includes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-admin
  - minimal-mistakes-jekyll
  - webrick
  - jekyll-admin
  

author:
  name   : "Eliabe da Silva"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Notícias, meliponicultura, tecnologia, tutoriais e muito mais!"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eliabesilvala"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eliabesilvala"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/eliabesilvala"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eliabesilvala"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eliabesilvala"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/eliabesilvala"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
